# repos:
#   - repo: https://github.com/realm/SwiftLint
#     rev: 0.57.1
#     hooks:
#       - id: swiftlint
#   - repo: https://github.com/realm/SwiftLint
#     rev: 0.57.1
#     hooks:
#       - id: swiftlint
#         entry: swiftlint --fix --strict