//
//  DkDamRemoconCode.swift
//  KaraokeSDK
//
//  Created by devonly on 2025/07/14.
//

public enum DkDamRemoconCode: String, Decodable, Sendable, CaseIterable {
    case stop = "00"
    case retry = "01"
    case switchSongMode = "03"
    case keyUp = "04"
    case keyDown = "05"
    case ruby = "06"
    case reserveList = "0A"
    case wipe = "0C"
    case guideMelody = "0D"
    case backward = "1A"
    case pause = "1B"
    case fastForward = "1C"
    case dam = "1D"
    case originalKey = "1E"
    case visibleGuideMelody = "1F"
    case tempoUp = "20"
    case tempoDown = "21"
    case guideVocal = "26"
    case maskOn = "28"
    case maskOff = "29"
    case notAvailable = "2F"
    case originalKeyRepeat = "60"
    case captionSize = "67"
    case volumeDown = "AD"
    case stopPlaying = "AE"
    case volumeUp = "AF"
    case toChorus = "B4"
    case visibleGuideMelodyRepeat = "B5"
    case up = "B7"
    case down = "B8"
    case left = "B9"
    case right = "BA"
    case captionDisplay = "BB"
    case guideMelodyLarge = "BE"
    case guideMelodyNormal = "BF"
    case guideMelodyOff = "C0"
    case guideVocalLarge = "C1"
    case guideVocalNormal = "C2"
    case guideVocalSmall = "C3"
    case guideVocalAssist = "C4"
    case guideVocalOff = "C5"
    case captionSizeLarge = "C6"
    case captionSizeNormal = "C7"
    case captionSizeSmall = "C8"
    case fadeOut2Chorus = "C9"
    case fadeOutEndCut = "CA"
    case fadeOutOff = "CB"
    case fadeOut1Chorus = "CE"
    case backChorus = "D0"
    case animeVoice = "D2"
    case femaleChange = "D3"
    case maleChange = "D4"
    case alienChange = "D5"
    case vibrato = "D6"
    case enkaVibrato = "D7"
    case technoVoice = "D8"
    case radioVoice = "D9"
    case doubleVoice = "DA"
    case duetWithMale = "DC"
    case duetWithFemale = "DD"
    case ageMinus5 = "DE"
    case agePlus5 = "DF"
    case agePlus10 = "E0"
    case fadeOut = "E8"
    case noMessage = "EA"
    case damVocalLarge = "EC"
    case damVocalNormal = "ED"
    case damVocalSmall = "EE"
    case damVocalAssist = "EF"
    case damVocalOff = "F0"
    case damVocal = "F1"
    case liveDome = "F4"
    case liveHall = "F5"
    case liveSoundOff = "F6"
    case tokyoDome = "F7"
    case nagoyaDome = "F9"
    case zeppTokyo = "FA"
    case fukuokaDome = "FB"
    case yokohamaArena = "FC"
}
